### ISSUE TITLE
Name Error in cell no. 13

### ISSUE THREAD

**Issue by abhishekt711** [vishwakarmarhl/rdd2020#1]
![image](https://user-images.githubusercontent.com/36338604/115613562-29ba2e80-a30a-11eb-87ac-718432a8e20c.png)
NameError                                 Traceback (most recent call last)
<ipython-input-123-5e4149b04a9d> in <module>()
     14         cv2_imshow(out.get_image()[:, :, ::-1])
     15 
---> 16 visualise_dataset()

1 frames
<ipython-input-118-44f6b4cc3ad5> in load_images_ann_dicts(basepath, splits_per_dataset)
     20             if os.path.isfile(os.path.join(ann_path, ann_file)):
     21                 infile_xml = open(os.path.join(ann_path, ann_file))
---> 22                 tree = ElementTree.parse(infile_xml)
     23                 root = tree.getroot()
     24                 img_height = int(root.find('size').find('height').text)

NameError: name 'ElementTree' is not defined

**Comment by karmarv** [comment]
Hey @abhishekt711 
have committed a new notebook that is tested on Colab. It uses a sample short dataset to run through the training and evaluation.
Link: https://github.com/vishwakarmarhl/rdd2020/blob/master/D2_rdd2020_colab.ipynb
